[versions]

appcompat = "1.8.0"
agp = "9.4.0"
preference = "1.2.1"
caupian = "1.10.1"

[plugins]

caupain = { id = "com.deezer.caupain", version.ref = "caupian" }

android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]

appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
